### ISSUE TITLE
Body A despawns when Body B is revived

### ISSUE THREAD

**Issue by MiniSvamp** [Sehelitar/Zaprillator#1]
Not sure how to title such a report, but during a (heavily modded) play session with a few of my friends we encountered an issue where reviving an employee whilst more than one body is present on the map, it deletes even the non-revived bodies. Location of the non-revived body relative to the revived one does not seem to affect anything.

Unfortunately, I had turned off logging (and also was not the host), so I have no relevant logs other than a description of the issue. I'll return with something more substancial and see if it's a mod conflict, or if it's just this mod sometime later (probably tomorrow).

**Comment by Sehelitar** [comment]
Hey 👋 
I checked if this case was possible, and I did find something.
I made a fix and submitted the update, it should be available in the store soon.
Thank you for the report 🙏
